export const COMPLITED = "Mua hàng thành công";
export const SUCCESS_ADD_TO_CART = "Thêm vào giỏ hàng thành công"
export const NO_PRODUCTS_IN_THE_CART = 'Giỏ hàng trống'
export const LOGIN_SUCCESS = 'Đăng nhập thành công';
export const REGISTER_SUCCESS = 'Đăng ký thành công';
export const FAILED_REGISTER = 'Đăng ký thất bại';
export const DELETE_CART_SUCCESS = 'Đã xóa sản phẩm khỏi giỏ hàng';
export const IS_LOGIN = 'Vui lòng đăng nhập trước khi thanh toán';
export const PAY_SUCCESS = 'Thanh toán thành công';
export const FAILED_LOGIN = "*Sai tên đăng nhập hoặc mật khẩu";
export const WARN_EMAIL = '*Vui lòng nhập email';
export const WARN_PASSWORD = '*Vui lòng nhập mật khẩu từ 6 kí tự';
export const CONFIRM_PASSWORD = '*Mật khẩu không trùng khớp';
export const WARN_USERNAME = '*Vui lòng nhập tên tài khoản';
export const WARN_USERNAME_2 = '*Tên quá ngắn, vui lòng nhập hơn 6 kí tự'
export const CHECK_EMAIL = '*Trường này phải là email';
export const ACCOUNT_REGISTER_USED = 'Email này đã được sử dụng';